apiVersion: v1
kind: Service
metadata:
  name: k8s-rbac-backend-service
spec:
  selector:
    app: k8s-rbac-backend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-rbac-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-rbac-backend
  template:
    metadata:
      labels:
        app: k8s-rbac-backend
    spec:
      serviceAccountName: k8s-rbac-admin
      containers:
        - name: k8s-rbac-backend
          image: k8s-rbac-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: KUBERNETES_SERVICE_HOST
              value: "kubernetes.default.svc"
            - name: KUBERNETES_SERVICE_PORT
              value: "443"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-rbac-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-rbac-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: k8s-rbac-admin
    namespace: default